import type { Tool } from '../../domain/tool';
import { toolConfigSchemaVersion, toolSchemaVersion } from '../../schemas/tool';

const now = new Date().toISOString();

export const seedTools: Tool[] = [
  {
    id: 'seed-weather-api',
    version: toolSchemaVersion,
    name: 'Weather Snapshot API',
    description: 'Fetches current weather observations for dashboard cards.',
    category: 'monitoring',
    tags: ['weather', 'dashboard'],
    type: 'rest_api',
    authType: 'none',
    endpoint: 'https://api.example.com/weather/current',
    method: 'GET',
    headers: [],
    samplePayload: '',
    configVersion: toolConfigSchemaVersion,
    config: {
      endpoint: 'https://api.example.com/weather/current',
      method: 'GET',
      headers: [],
      samplePayload: '',
    },
    status: 'configured',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'seed-tasks-api',
    version: toolSchemaVersion,
    name: 'Task Sync Endpoint',
    description: 'Synchronizes task metadata between local and cloud providers.',
    category: 'operations',
    tags: ['tasks', 'sync'],
    type: 'openai_compatible',
    authType: 'api_key',
    credentialRefId: 'OPENAI_API_KEY',
    endpoint: 'https://api.example.com/tasks/sync',
    method: 'POST',
    headers: [],
    samplePayload: '{"model":"gpt-4o-mini","messages":[{"role":"user","content":"ping"}]}',
    configVersion: toolConfigSchemaVersion,
    config: {
      endpoint: 'https://api.example.com/tasks/sync',
      headers: [],
      samplePayload: '{"model":"gpt-4o-mini","messages":[{"role":"user","content":"ping"}]}',
    },
    status: 'missing_credentials',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'seed-notify-webhook',
    version: toolSchemaVersion,
    name: 'Release Notify Webhook',
    description: 'Posts release notifications to external channels.',
    category: 'automation',
    tags: ['releases', 'notifications'],
    type: 'webhook',
    authType: 'custom_header',
    credentialRefId: 'WEBHOOK_SECRET',
    customHeaderName: 'X-Webhook-Secret',
    endpoint: 'https://hooks.example.com/releases',
    method: 'POST',
    headers: [],
    samplePayload: '{"event":"release.published"}',
    configVersion: toolConfigSchemaVersion,
    config: {
      endpoint: 'https://hooks.example.com/releases',
      method: 'POST',
      headers: [],
      samplePayload: '{"event":"release.published"}',
    },
    status: 'disabled',
    createdAt: now,
    updatedAt: now,
  },
];
